import csv
import time
import os
import re

import requests
import pandas as pd

from harvesters.base import BaseHarvester
from utils.distribution_writer import generate_secondary_table
from utils.temporal_fields import infer_temporal_coverage_from_title, create_date_range


class SocrataHarvester(BaseHarvester):
    def __init__(self, config):
        super().__init__(config)

    def load_reference_data(self):
        super().load_reference_data()

    def fetch(self):
        hub_file = self.config.get("hub_list_csv")
        with open(hub_file, newline='', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                hub_id = row['ID']
                url = row['Endpoint URL']
                try:
                    resp = requests.get(url, timeout=30)
                    resp.raise_for_status()
                    data = resp.json()
                except Exception as e:
                    yield f"[Socrata] Error fetching {hub_id}: {e}"
                    continue

                row['raw_data'] = data
                yield f"[Socrata] Fetched {hub_id} — {row.get('Title', 'No Title')}"
                yield row


    # def parse(self, fetched_records):
    #     not needed

    def flatten(self, parsed_data):
        """
        De-nest raw_data['dataset'] records into a list of dicts,
        each containing 'hub' and 'ds' keys.
        """
        flattened = []

        for rec in parsed_data:
            if not isinstance(rec, dict):
                continue

            datasets = rec.get("raw_data", {}).get("dataset", [])
            if isinstance(datasets, dict):
                datasets = [datasets]  # normalize edge case

            for ds in datasets:
                flattened.append({"hub": rec, "ds": ds})

        return flattened

    def build_dataframe(self, flattened_items):
        """
        Convert flattened [{'hub':..., 'ds':...}] list to a fully structured DataFrame.
        """
        df = pd.DataFrame(flattened_items)

        df = (
            df.pipe(self.socrata_filter_rows)
            .pipe(self.socrata_normalize_fields)
            .pipe(self.socrata_map_to_schema)
        )

        return df


    def derive_fields(self, df):
        df['ID'] = df['Identifier'].str.split('/views/', n=1).str[-1]
        df['Temporal Coverage'] = df['Date Modified']

        df = (
            df.pipe(self.socrata_clean_descriptions)
            .pipe(self.socrata_temporal_coverage)
            .pipe(self.socrata_format_date_ranges)
            .pipe(self.socrata_reformat_titles)
            .pipe(self.pasda_derive_geojson)
        )

        return df


    def add_defaults(self, df):
        df = super().add_defaults(df)

        df['Display Note'] = "Tip: Check “Visit Source” link for download options."
        df['Language'] = 'eng'
        df['Access Rights'] = 'Public'
        df['Resource Class'] = 'Web services'
        return df
    
    def add_provenance(self, df: pd.DataFrame) -> pd.DataFrame:
        # ---------- inherited defaults ----------
        df = super().add_provenance(df)

        today = time.strftime("%Y-%m-%d")

        # ---------- provenance fields for harvested dataset rows ----------
        df["Source Platform"] = "Socrata"
        df["Accrual Method"] = "Scripted harvest"
        df["Was Generated By"] = "R02_socrata"
        df["Supported Metadata Schema"] = "DCAT-US Schema v1.1"
        df["Endpoint Description"] = "DCAT API"
        df["Provenance Statement"] = df.apply(
            lambda row: (
                f"The metadata for this resource was last retrieved from "
                f"{row.get('Local Collection', ' Open Data Portal')} on {today}."
            ),
            axis=1,
        )

        # ---------- load hub list and evaluate indexing status ----------
        hub_path = self.config.get("hub_list_csv")

        if hub_path and os.path.exists(hub_path):
            hub_df = pd.read_csv(hub_path, dtype=str).fillna("")

            # Ensure required columns exist
            if "Status" not in hub_df.columns:
                hub_df["Status"] = ""

            # Convert to string for a reliable comparison
            indexed_ids = set(df["Is Part Of"].astype(str))

            hub_df["Status"] = hub_df["ID"].apply(
                lambda hub_id: "Indexed" if str(hub_id) in indexed_ids else "Not indexed"
            )

            hub_df["Date Accessioned"] = today


            # ---------- merge ----------
            df = pd.concat([df, hub_df], ignore_index=True)

            print(f"[Socrata] Updated Status for {len(hub_df)} hub records and "
                f"appended them to the harvested metadata dataframe.")
        else:
            print("[Socrata] hub_list_csv not found or unspecified.")

        return df



    def clean(self, df):
        df = super().clean(df)
        return df

    def validate(self, df):
        df = super().validate(df)
        return df

    def write_outputs(self, primary_df, distributions_df=None):
        distributions_df = generate_secondary_table(primary_df.copy(), self.distribution_types)
        return super().write_outputs(primary_df, distributions_df)

# --- Socrata Specific Field Derive Functions --- #

    def socrata_filter_rows(self, df):
        def is_valid(row):
            ds = row['ds']
            title = (ds.get('title') or '').strip()
            if not title or title.startswith('{{'):
                return False

            keywords = [k.lower().strip() for k in ds.get('keyword', []) if isinstance(k, str)]
            themes = [t.lower().strip() for t in ds.get('theme', [])] if isinstance(ds.get('theme'), list) else []

            return 'gis' in keywords or 'gis/maps' in themes

        return df[df.apply(is_valid, axis=1)].reset_index(drop=True)
    
    def socrata_normalize_fields(self, df):
        def get_creator(ds):
            pub = ds.get('publisher')
            if isinstance(pub, dict):
                return pub.get('name') or next(iter(pub.values()), '')
            return pub or ''

        df['title'] = df['ds'].apply(lambda d: (d.get('title') or '').strip())
        df['description'] = df['ds'].apply(lambda d: d.get('description', ''))
        df['keywords'] = df['ds'].apply(lambda d: d.get('keyword', []) or [])
        df['themes'] = df['ds'].apply(lambda d: d.get('theme', []) or [])
        df['creator'] = df['ds'].apply(get_creator)
        df['issued'] = df['ds'].apply(lambda d: (d.get('issued', '') or '').split('T')[0])
        df['modified'] = df['ds'].apply(lambda d: (d.get('modified', '') or '').split('T')[0])
        df['license'] = df['ds'].apply(lambda d: d.get('license', ''))
        df['identifier_raw'] = df['ds'].apply(lambda d: d.get('identifier', ''))
        df['landingPage'] = df['ds'].apply(lambda d: d.get('landingPage', ''))
        

        return df
    
    def socrata_map_to_schema(self, df):
        df_out = pd.DataFrame()

        # From input CSV
        df_out['Is Part Of'] = df['hub'].apply(lambda h: h.get('ID', ''))
        df_out['Code'] = df['hub'].apply(lambda h: h.get('ID', ''))
        df_out['Local Collection'] = df['hub'].apply(lambda h: h.get('Title', ''))
        df_out['Publisher'] = df['hub'].apply(lambda h: h.get('Creator', ''))
        df_out['Endpoint URL'] = df['hub'].apply(lambda h: h.get('Endpoint URL', ''))
        df_out['Spatial Coverage'] = df['hub'].apply(lambda h: h.get('Spatial Coverage', ''))
        df_out['Bounding Box'] = df['hub'].apply(lambda h: h.get('Bounding Box', ''))
        df_out['Member Of'] = df['hub'].apply(lambda h: h.get('Member Of', ''))
        df_out['Publisher'] = df['hub'].apply(lambda h: h.get('Publisher', ''))
        df_out['titlePlace'] = df['hub'].apply(lambda h: h.get('Publisher', ''))

        # Fields to harvest from DCAT API
        df_out['Alternative Title'] = df['title']
        df_out['Description'] = df['description']
        df_out['Creator'] = df['creator']
        df_out['Keyword'] = df['keywords'].apply(lambda lst: '|'.join(k.strip() for k in lst if isinstance(k, str)).replace(' ', ''))
        df_out['Subject'] = df['themes'].apply(lambda lst: '|'.join(lst) if isinstance(lst, list) else lst)
        df_out['Date Issued'] = df['issued']
        df_out['Date Modified'] = df['modified']
        df_out['Rights'] = df['license']
        df_out['Identifier'] = df['identifier_raw']
        df_out['information'] = df['landingPage']

        return df_out
    
    def socrata_temporal_coverage(self, df):
        """
        Adds a 'Temporal Coverage' column based on Title or Date Modified.
        """
        df["Temporal Coverage"] = df.apply(infer_temporal_coverage_from_title, axis=1)
        return df
    
    def socrata_format_date_ranges(self, df):
        """
        Adds a 'Date Range' column based on 'Temporal Coverage', 'Date Modified', or 'Date Issued'.
        """
        df["Date Range"] = df.apply(
            lambda row: create_date_range(row, row.get("Temporal Coverage", "")),
            axis=1
        )
        return df

    def socrata_reformat_titles(self, df):
        """
        Updates the Title field by concatenating 'Alternative Title' and 'titlePlace',
        with the titlePlace in square brackets. Handles missing values gracefully.
        Example: "IDOT Waterway Ferries [Illinois]"
        """
        df['Title'] = df.apply(
            lambda row: f"{row['Alternative Title']} [{row['titlePlace']}]"
            if pd.notna(row['Alternative Title']) and pd.notna(row['titlePlace'])
            else row['Alternative Title'] if pd.notna(row['Alternative Title'])
            else f"[{row['titlePlace']}]" if pd.notna(row['titlePlace'])
            else "",
            axis=1
        )
        return df
    
    def socrata_clean_descriptions(self, df):
        def _clean(text):
            text = text.replace("{{default.description}}", "").replace("{{description}}", "")
            text = re.sub(r'[\n\r]+', ' ', text)
            text = re.sub(r'\s{2,}', ' ', text)
            return text.translate({
                8217: "'",  # RIGHT SINGLE QUOTATION MARK → apostrophe
                8220: '"',  # LEFT DOUBLE QUOTATION MARK → "
                8221: '"',  # RIGHT DOUBLE QUOTATION MARK → "
                160: "",    # NON-BREAKING SPACE → removed
                183: "",    # MIDDLE DOT → removed
                8226: "",   # BULLET → removed
                8211: '-',  # EN DASH → hyphen
                8203: ""    # ZERO WIDTH SPACE → removed
            })
        df['Description'] = df['Description'].apply(_clean)
        return df
    
    def pasda_derive_geojson(self, df):
        """
        Add a 'geojson' distribution link for certain hubs (e.g., PASDA).
        Uses the hub Identifier (portal base URL) and the dataset's ID.
        """
        allowed_hubs = {'01c-01', '12b-17031-2'}

        # For this to work, we need hub-level info carried over from socrata_map_to_schema.
        # You can add 'Hub ID' and 'Hub Identifier' there if not already present.
        if 'Hub ID' not in df.columns:
            df['Hub ID'] = df['Is Part Of']
        if 'Hub Identifier' not in df.columns:
            df['Hub Identifier'] = df['Endpoint URL'].str.rsplit('/data.json', n=1).str[0]

        def build_geojson(row):
            if row['Hub ID'] in allowed_hubs and pd.notna(row['Hub Identifier']) and pd.notna(row['ID']):
                base = str(row['Hub Identifier']).rstrip('/')
                return f"{base}/resource/{row['ID']}.geojson"
            return ''

        df['geo_json'] = df.apply(build_geojson, axis=1)
        return df

